import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@components/navbar";
import Notifications from "@components/Notifications";
import AuthSession from "./components/AuthSession";

export const metadata: Metadata = {
  title: "AKM Ecommerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthSession>
          <Navbar />
          {children}
          <Notifications />
        </AuthSession>
      </body>
    </html>
  );
}
